### ISSUE TITLE
Templatize the file structure by binding with template data defined in boilerplato.yml config

### ISSUE THREAD

**Issue by rousan** [boilerplato/boilerplato#5]
As of now, if someone needs to add/remove a file/folder based on user inputs, he/she will have to write scripts for that. To resolve that, we can templatize folder structure based on user inputs defined boilerplato.yml file.

An example:

```yml
- files:
  - "src/store": "{{ isReduxIncluded }}"
  - "src/history.js": "{{ isRouterIncluded }}"
```

the condition will be a handlebars formatted string and whose output will be a truthy value or falsy values and if it is truthy, the file/folder will be processed by the generators otherwise, it will be ignored.
